[package]
name = "unseemly"
version = "0.0.0"
authors = ["Paul Stansifer <paul.stansifer@gmail.com>"]

[dependencies]
lazy_static = { version = "0.2.1" }
regex = { version = "0.1.77" }
combine = { version = "1.3.0" } # TODO: upgrade to 2.*
num = { version = "0.1.36" }
custom_derive = { version = "0.1.5" }

[[bin]]
name = "unseemly"
path = "src/main.rs"
test = true
