[package]
name = "unseemly"
version = "0.0.0"
authors = ["Paul Stansifer <paul.stansifer@gmail.com>"]

[dependencies]
lazy_static = { version = "0.1.16" }
regex = { version = "0.1.66" }
combine = { version = "1.3.0" } 
num = { version = "0.1.32" }
custom_derive = { version = "0.1.5" }

[[bin]]
name = "unseemly"
path = "src/main.rs"
test = true
