[package]
name = "unseemly"
version = "0.0.0"
authors = ["Paul Stansifer <paul.stansifer@gmail.com>"]

[dependencies]
lazy_static = { version = "0.2.1" }
regex = { version = "0.1.77" }
num = { version = "0.1.36" }
custom_derive = { version = "0.1.5" }
lalrpop-intern = { version = "0.12.4" }
mac = "0.1.1"
quote = "0.3"
rustyline = "1.0.0"
dirs = "1.0.3"

[[bin]]
name = "unseemly"
path = "src/main.rs"
test = true
